# To create/update this environment, run:
#   conda env create -f environment.yml

# To fully re-build the environment from scratch, run:
#   conda env remove -n monstim
#   conda clean --all
#   conda env create -f environment.yml

name: monstim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14.*
  - numpy=2.4.2
  - pandas=3.0.0
  - matplotlib=3.10.8
  - scipy=1.17.0
  - h5py=3.15.1
  - pyyaml=6.0.3
  - packaging=26.0
  - traitlets=5.14.3
  - pillow=12.1.0
  - pyside6=6.9.3
  - pyqtgraph=0.14.0
  - pip
  - pip:
      - openpyxl>=3.1
      - Markdown==3.10.2
      - python_markdown_math==0.9
      - pytest==9.0.1
      - setuptools==82.0.0


