# To create/update this environment, run:
#   conda env create -f environment.yml

# To fully re-build the environment from scratch, run:
#   conda env remove -n alv_lab
#   conda clean --all
#   conda env create -f environment.yml

name: alv_lab
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.2.6
  - pandas=2.3.3
  - matplotlib=3.10.7
  - scipy=1.15.3
  - h5py=3.15.1
  - pyyaml=6.0.3
  - packaging=25.0
  - traitlets=5.14.3
  - pillow=12.0.0
  - pyside6=6.9.3
  - pyside6-addons=6.9.3
  - qt6-webengine=6.9.*
  - pyqtgraph=0.14.0
  - pip
  - pip:
      - Markdown==3.10
      - python_markdown_math==0.9
      - pytest==9.0.0
      - setuptools==80.9.0


