name: alv_lab
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313hf069bd2_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - double-conversion=3.3.1=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py313hd650c13_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h5py=3.15.1=nompi_py313hf7f959b_101
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - icc_rt=2022.1.0=h6049295_2
  - icu=75.1=he0c23c2_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=20_win64_mkl
  - libclang13=21.1.6=default_ha2db4b5_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_14
  - libglib=2.86.2=hd9c3897_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=20_win64_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.51=h7351971_0
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=h29ce207_0
  - matplotlib=3.10.7=py313hfa70ccb_0
  - matplotlib-base=3.10.7=py313he1ded55_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.1=py313hc583439_1
  - munkres=1.1.4=py_0
  - numpy=2.2.6=py313hefb8edb_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_2
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py313h38f99e1_2
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqtgraph=0.14.0=pyhd8ed1ab_0
  - pyside6=6.9.3=py313h475ba69_1
  - python=3.13.9=h09917c8_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313hd650c13_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - scipy=1.15.3=py313hde77213_0
  - six=1.16.0=pyhd3eb1b0_1
  - tbb=2021.13.0=hd094cb3_4
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py313h5ea7bf4_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - yaml=0.2.5=h6a83c73_3
  - zlib-ng=2.3.1=h5112557_1
  - zstd=1.5.7=h1b5488d_5
  - pip:
      - altgraph==0.17.5
      - iniconfig==2.3.0
      - markdown==3.10
      - pefile==2024.8.26
      - pluggy==1.6.0
      - pygments==2.19.2
      - pyinstaller==6.17.0
      - pyinstaller-hooks-contrib==2025.10
      - pytest==9.0.0
      - python-markdown-math==0.9
      - pywin32-ctypes==0.2.3
      - setuptools==80.9.0
prefix: C:\Users\aewor\miniconda3\envs\alv_lab

